query active_agencies($feed_version_sha1: String, $geometry: geography) {
  count: active_agencies_aggregate {
    aggregate {
      count
    }
  }
  entities: active_agencies(where: {feed_version: {sha1: {_eq: $feed_version_sha1}}, agency_geometry: {centroid: {_st_intersects: $geometry}}}, order_by: {agency_id: asc}) {
    agency_email
    agency_fare_url
    agency_id
    agency_lang
    agency_name
    agency_phone
    agency_timezone
    agency_url
    feed_version_id
    id
    agency_geometry {
      centroid
    }
  }
}
