query current_feeds($onestop_id: String, $last_fetch_error: String, $geometry: geography) {
  count: current_feeds_aggregate {
    aggregate {
      count
    }
  }
  entities: current_feeds(order_by: {id: asc}, where: {feed_state: {last_fetch_error: {_neq: $last_fetch_error}, _or: [{feed_version_id: {_is_null: true}}, {feed_version: {geometry: {centroid: {_st_intersects: $geometry}}}}]}}) {
    id
    onestop_id
    feed_state {
      last_fetch_error
      last_fetched_at
      last_successful_fetch_at
      feed_version {
        geometry {
          centroid
        }
        id
      }
    }
    feed_versions_aggregate {
      aggregate {
        count
      }
    }
  }
}
