query active_agencies($agency_name: String, $city_name: String, $admin_name: String, $country_name: String, $offset: Int, $limit: Int) {
  count: active_agencies_aggregate(where: {agency_name: {_like: $agency_name}, tl_agency_places: {name: {_ilike: $city_name}, adm1name: {_ilike: $admin_name}, adm0name: {_ilike: $country_name}}}) {
    aggregate {
      count
    }
  }
  active_agencies(limit: $limit, offset: $offset, order_by: {agency_name: asc}, where: {agency_name: {_like: $agency_name}, tl_agency_places: {name: {_ilike: $city_name}, adm1name: {_ilike: $admin_name}, adm0name: {_ilike: $country_name}}}) {
    id
    agency_name
    agency_url
    tl_agency_places(limit: 1, order_by: {rank: desc}, where: {name: {_is_null: false}}) {
      name
      adm1name
      adm0name
      rank
    }
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
  }
}
