query ($offset: Int!, $limit: Int!, $name: String, $city_name: String, $adm1name: String, $adm0name: String) {
  entities: tl_agency_operators(offset: $offset, limit: $limit, where: {agency: {agency_name: {_eq:$name}, places: {name: {_eq: $city_name}, adm0name: {_eq: $adm0name}, adm1name: {_eq: $adm1name}}}}) {
    operator_by_feed_namespace {
      id
      name
      onestop_id
    }
    operator_by_feed {
      id
      name
      onestop_id
    }
    operator_by_agency {
      id
      name
      onestop_id
    }
    agency {
      id
      agency_name
      places(order_by: {rank: desc, adm1name: desc}) {
        rank
        city_name: name
        adm0name
        adm1name
        best_match
        best_match_type
      }
    }
  }
}
