query ($onestop_id: String, $feed_version_sha1: String, $feed_onestop_id: String, $agency_id: String, $active_null: Boolean) {
  entities: tl_mv_active_agency_operators(limit: 100, where: {feed_onestop_id: {_eq:$feed_onestop_id}, onestop_id: {_eq:$onestop_id}}) {    
    onestop_id
    agency_name
    operator_name
    city_name
    adm1name
    adm0name
    operator {
      id
      name
      onestop_id
      associated_feeds
      tags
    }
    agency {
      id
      feed_version_id
      feed_version_sha1
      feed_onestop_id
      agency_id
      agency_name
      agency_url
      agency_phone
      feed_version {
        id
        fetched_at
        current_feed {
          id
          onestop_id
          feed_namespace_id
        }
      }
      places(where: {rank: {_gt: 0.2}}) {
        name
        adm0name
        adm1name
      }
    }
  }
}
