
query current_feeds($specs: [String!]) {
  current_feeds(order_by: {id: asc}, where: {spec: {_in: $specs}, deleted_at: {_is_null: true}}) {
    onestop_id
    spec
    feed_versions_aggregate {
      aggregate {
        count
      }
    }
    feed_state {
      feed_version {
        feed_version_gtfs_import {
          id
          created_at
        }
      }
      last_fetch_error
      last_fetched_at
      last_successful_fetch_at
    }
    import_errors: feed_versions(where: {feed_version_gtfs_import: {success: {_eq: false}, in_progress: {_eq: false}}}, order_by: {id: desc}) {
      id
      feed_version_gtfs_import {
        created_at
        success
        in_progress
        exception_log
      }
    }
  }
}
