query current_feeds($feed_onestop_id: String) {
  entities: current_feeds(where: {onestop_id: {_eq: $feed_onestop_id}}, limit: 1) {
    id
    auth
    onestop_id
    associated_feeds
    created_at
    deleted_at
    feed_namespace_id
    languages
    license
    onestop_id
    other_ids
    spec
    urls
    feed_versions(order_by: {fetched_at: desc}) {
      id
      sha1
      earliest_calendar_date
      latest_calendar_date
      fetched_at
      url
      feed_version_gtfs_import {
        id
        success
        in_progress
        created_at
      }
    }
    feed_state {
      last_fetch_error
      last_fetched_at
      last_successful_fetch_at
      feed_version {
        id
        routes {
          id
          route_id
          route_type
          route_short_name
          route_long_name
        }
      }
    }
  }
}
