query current_operators($operator_onestop_id: String) {
  entities: tl_agency_operator_associations(where: {operator_onestop_id: {_eq: $operator_onestop_id}}) {
    operator_id
    operator_name
    agency_id
    agency {
      id
      agency_id
      agency_name
      feed_version {
        id
        current_feed {
          id
          onestop_id
        }
      }
    }
    associated_feeds
    city_name
    country_name
    group_id
    operator_onestop_id
    operator_short_name
    state_name
  }
}
