
query current_feeds($specs: [String!], $check_no_fetch_error:String, $check_last_fetch_error:String, $offset:Int, $limit:Int = 100) {
  count: current_feeds_aggregate(where: {spec: {_in: $specs}, deleted_at: {_is_null: true}, feed_state:{last_fetch_error:{_eq:$check_no_fetch_error,_neq:$check_last_fetch_error}}}) {
    aggregate {
      count
    }
  }
  entities: current_feeds(offset:$offset, limit:$limit, order_by: {id: asc}, where: {spec: {_in: $specs}, deleted_at: {_is_null: true}, feed_state:{last_fetch_error:{_eq:$check_no_fetch_error,_neq:$check_last_fetch_error}}}) {
    id
    onestop_id
    spec
    feed_versions_aggregate {
      aggregate {
        count
      }
    }
    feed_state {
      id
      feed_version {
        id
        feed_version_gtfs_import {
          id
          created_at
        }
      }
      last_fetch_error
      last_fetched_at
      last_successful_fetch_at
    }
    import_errors: feed_versions(where: {feed_version_gtfs_import: {success: {_eq: false}, in_progress: {_eq: false}}}, order_by: {id: desc}) {
      id
      feed_version_gtfs_import {
        created_at
        success
        in_progress
        exception_log
      }
    }
  }
}
