query ($operator_onestop_id: String!) {
  operators: current_operators(where: {onestop_id: {_eq:$operator_onestop_id}}) {    
      id
      name
      onestop_id
      associated_feeds
  }
  matches: tl_agency_operators(where: {operator_onestop_id: {_eq:$operator_onestop_id}}) {    
    id
    agency_name
    operator_name
    city_name
    adm1name
    adm0name
    operator_onestop_id
    operator {
      id
      name
      onestop_id
    }
    agency {
      feed_version { 
        id
        sha1
        current_feed {
          id
          feed_namespace_id
          onestop_id
        }
      }
      id
      agency_name
      agency_url
      agency_phone
      agency_id
      places(where: {rank: {_gt: 0.2}}, order_by: {rank: desc, adm1name: desc}) {
        rank
        name
        adm0name
        adm1name
        best_match
        best_match_type
      }
    }
  }
}
