query current_feeds(
  $limit: Int = 100
) {
  entities: current_feeds(
    limit: $limit 
  ) {
    id
    onestop_id
    spec
    feed_state {
      id
      feed_version {
        id
        feed_version_gtfs_import {
          id
        }
      }
      last_fetch_error
      last_fetched_at
      last_successful_fetch_at
    }
    import_errors: feed_versions {
      id
      feed_version_gtfs_import {
        id
        success
        in_progress
        exception_log
      }
    }
  }
}
