query ($feed_version_ids: [bigint!], $offset: Int!, $limit: Int!, $agency_ids:[bigint!], $route_ids: [bigint!], $order_by:[gtfs_routes_order_by!])
 {
  total: gtfs_routes_aggregate(where: {agency_id:{_in:$agency_ids}, feed_version_id: {_in: $feed_version_ids}, id: {_in: $route_ids}}) {
    aggregate {
      count
    }
  }
  routes: gtfs_routes(limit: $limit, where: {agency_id:{_in:$agency_ids}, feed_version_id: {_in: $feed_version_ids}, id: {_in: $route_ids}}, order_by: $order_by, offset: $offset) {
    id
    feed_version_id
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
    route_id
    route_short_name
    route_long_name
    route_url
    agency {
      id
      agency_id
      agency_name
    }
    headways {
      selected_stop_id
      service_date
      dow_category
      headway_seconds_morning_min
      headway_seconds_midday_min
      headway_seconds_evening_min
      headway_seconds_latenight_min
      headway_seconds_morning_mid
      headway_seconds_midday_mid
      headway_seconds_evening_mid
      headway_seconds_latenight_mid
      headway_seconds_morning_max
      headway_seconds_midday_max
      headway_seconds_evening_max
      headway_seconds_latenight_max
    }
    headways_weekday {
      headway_seconds_morning_min
      headway_seconds_morning_mid
      headway_seconds_morning_max
    }
  }
}
