query ($feed_version_ids: [bigint!], $offset: Int!, $limit: Int!, $stop_ids: [bigint!], $agency_ids: [bigint!], $route_ids: [bigint!], $order_by:[gtfs_stops_order_by!]) {
  total: gtfs_stops_aggregate(where: {feed_version_id: {_in: $feed_version_ids}, id: {_in: $stop_ids}, route_stops: {agency_id: {_in: $agency_ids}, route_id: {_in: $route_ids}}}) {
    aggregate {
      count
    }
  }
  stops: gtfs_stops(limit: $limit, order_by: $order_by, offset: $offset, where: {feed_version_id: {_in: $feed_version_ids}, id: {_in: $stop_ids}, route_stops: {agency_id: {_in: $agency_ids}, route_id: {_in: $route_ids}}}) {
    id
    stop_id
    stop_name
    stop_code
    stop_desc
    stop_url
    location_type
    wheelchair_boarding
    route_stops {
      route {
        id
        route_id
        route_short_name
        route_long_name
      }
      agency {
        id
        agency_id
        agency_name
      }
    }
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
  }
}
