query($feed_onestop_id: String!, $feed_version_sha1: String!, $stop_id: String!) {
  active_stops(limit: 1, where: {stop_id: {_eq: $stop_id}, feed_version: {current_feed: {onestop_id: {_eq: $feed_onestop_id}}}}) {
    feed_version_id
    id
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
    stop_name
    geometry
  }
  gtfs_stops(limit: 1, where: {feed_version: {sha1: {_eq: $feed_version_sha1}}, stop_id: {_eq: $stop_id}}) {
    feed_version_id
    id
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
    stop_name
    geometry
  }
}
