query ($onestop_id: String, $active_null: Boolean, $route_id: String, $feed_onestop_id: String, $feed_version_sha1: String) {
  entities: tl_vw_gtfs_routes(limit: 100, order_by: {id: desc}, where: {onestop_id: {_eq: $onestop_id}, feed_onestop_id:{_eq:$feed_onestop_id}, feed_version_sha1:{_eq:$feed_version_sha1}, route_id:{_eq:$route_id}, active: {_is_null: $active_null}}) {
    id
    onestop_id
    feed_onestop_id
    feed_version_sha1
    route_id
    route_color
    route_desc
    route_long_name
    route_short_name
    route_type
    route_url
    geometry
    route_stops {
      stop {
        id
        stop_id
        stop_name
        geometry
      }
    }
    agency {
      id
      agency_id
      agency_name
    }
    operator {
      id
      operator_name
      agency_name
      operator_onestop_id
    }
    headways {
      selected_stop_id
      dow_category
      service_date
      direction_id
      headway_secs
      headway_seconds_morning_min
      headway_seconds_midday_min
      headway_seconds_afternoon_min
      headway_seconds_night_min
      headway_seconds_morning_mid
      headway_seconds_midday_mid
      headway_seconds_afternoon_mid
      headway_seconds_night_mid
      headway_seconds_morning_max
      headway_seconds_midday_max
      headway_seconds_afternoon_max
      headway_seconds_night_max
    }
    feed_version {
      id
      fetched_at
    }
  }
}