query ($feed_version_sha1: String, $offset: Int!, $limit: Int!, $agency_id: String, $agency_name: String) {
  total: gtfs_agencies_aggregate(where: {feed_version: {sha1: {_eq: $feed_version_sha1}}, agency_id: {_ilike: $agency_id}, agency_name: {_ilike: $agency_name}}) {
    aggregate {
      count
    }
  }
  entities: gtfs_agencies(limit: $limit, where: {feed_version: {sha1: {_eq: $feed_version_sha1}}, agency_id: {_ilike: $agency_id}, agency_name: {_ilike: $agency_name}}, order_by: {agency_id: desc}, offset: $offset) {
    id
    agency_id
    agency_name
    agency_url
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
  }
}
