query ($feed_version_sha1: String!) {
  feed_versions(limit: 1, where: {sha1: {_eq: $feed_version_sha1}}) {
    id
    sha1
    earliest_calendar_date
    latest_calendar_date
    url
    feed_type
    fetched_at
    agencies_aggregate {
      aggregate {
        count
      }
    }
    routes_aggregate {
      aggregate {
        count
      }
    }
    stops_aggregate {
      aggregate {
        count
      }
    }
    feed_version_gtfs_import {
      id
      exception_log
      generated_count
      in_progress
      interpolated_stop_time_count
      skip_entity_error_count
      skip_entity_filter_count
      skip_entity_marked_count
      skip_entity_reference_count
      success
      warning_count
      entity_count
      created_at
    }
    geometry {
      geometry
    }
    file
  }
}
