query ($feed_version_ids: [bigint!], $offset: Int!, $limit: Int!, $agency_ids: [bigint!], $route_ids: [bigint!], $include_stops: Boolean!=false) {
  routes: tl_vw_gtfs_routes(limit: $limit, where: {agency_id:{_in:$agency_ids}, feed_version_id: {_in: $feed_version_ids}, id: {_in: $route_ids}}, order_by: {id: asc}, offset: $offset) {
    id
    onestop_id
    feed_onestop_id
    feed_version_sha1
    route_id
    route_color
    route_desc
    route_long_name
    route_short_name
    route_type
    route_url
    geometry
    route_stops @include(if: $include_stops) {
      stop {
        id
        stop_id
        stop_name
        geometry
      }
    }
    agency {
      id
      agency_id
      agency_name
    }
    headways_weekday {
      headway_secs
    }    
  }
}