query ($feed_version_ids: [bigint!], $offset: Int!, $limit: Int!, $agency_ids: [bigint!], $route_ids: [bigint!], $include_stops: Boolean!=false) {
  features: gtfs_routes(limit: $limit, where: {agency_id:{_in:$agency_ids}, feed_version_id: {_in: $feed_version_ids}, id: {_in: $route_ids}}, order_by: {id: asc}, offset: $offset) {
    id
    route_id
    route_type
    route_color
    route_short_name
    route_long_name
    headways_weekday {
      headway_secs
    }
    feed_version {
      id
      sha1
      current_feed {
        id
        onestop_id
      }
    }
    geometries {
      geometry
    }
    agency {
      id
      agency_name
    }
    route_stops @include(if: $include_stops) {
      stop {
        id
        geometry
      }
    }    
  }
}